"""bla

Revision ID: 100fff86efec
Revises: 9dd19732d8a2
Create Date: 2023-12-23 08:38:39.180844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100fff86efec'
down_revision = '9dd19732d8a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
