"""+2

Revision ID: 9dd19732d8a2
Revises: 0e6d2e53e3dc
Create Date: 2023-12-23 08:08:53.831759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd19732d8a2'
down_revision = '0e6d2e53e3dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
